package com.adept.ims.authorization.database.pojo;
// Generated Feb 10, 2009 8:20:02 PM by Hibernate Tools 3.2.1.GA

import com.adept.ims.common.database.pojo.BasePojo;
import java.io.Serializable;



/**
 * Authorities generated by hbm2java
 */
public class Authorities extends BasePojo  implements java.io.Serializable {


     private long id;
     
     private String authority;
     private Users  users;

    public Authorities() {
    }

    public Authorities(long id,  String authority,Users  users) {
       this.id = id;
       
       this.authority = authority;
       this.users = users;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

@Override
    public Object clone() {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Compare with other object
     * @param o
     * @return -1 if current object is less then other object
    0  if current object is equal to other object
    1  if current object is greater then other objct
     */
    @Override
    public int compareTo(Object o) {
        // TODO Auto-generated method stub
        return 0;
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        // TODO Auto-generated method stub
        return getId();
    }


}


