package com.adept.ims.authorization.database.pojo;
// Generated Feb 10, 2009 8:20:02 PM by Hibernate Tools 3.2.1.GA

import com.adept.ims.common.database.pojo.BasePojo;
import java.io.Serializable;




/**
 * Users generated by hbm2java
 */
public class Users extends BasePojo  implements java.io.Serializable {


     private String username;
     private String password;
     private boolean enabled;

    public Users() {
    }

    public Users(String username, String password, boolean enabled) {
       this.username = username;
       this.password = password;
       this.enabled = enabled;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public Object clone() {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Compare with other object
     * @param o
     * @return -1 if current object is less then other object
    0  if current object is equal to other object
    1  if current object is greater then other objct
     */
    @Override
    public int compareTo(Object o) {
        // TODO Auto-generated method stub
        return 0;
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        // TODO Auto-generated method stub
        return getUsername();
    }




}


